class DepositThread extends Thread {
    public void run(){
        System.out.println("Deposit Transaction started by "+Thread.currentThread().getName());
    }
}

class WithdrawThread extends Thread {
    public void run(){
        System.out.println("Withdrawal Transaction started by "+Thread.currentThread().getName());
    }
}

class BalanceCheck implements Runnable {
    public void run(){
        System.out.println("Balance Check started by "+Thread.currentThread().getName());
    }
}

class MiniStatement implements Runnable {
    public void run(){
        System.out.println("Mini Statement generated by "+Thread.currentThread().getName());
    }
}

public class BankTransaction {
    public static void main(String[] args){
        
        DepositThread t1 = new DepositThread();
        WithdrawThread t2 = new WithdrawThread();
        
        Thread t3 = new Thread(new BalanceCheck());
        Thread t4 = new Thread(new MiniStatement());

        t1.start();
        t2.start();
        t3.start();
        t4.start();
    }
}
